Importing the Required Libraries

In [97]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Reading the Dataset

In [98]:
data = pd.read_csv('Loan_Dataset.csv')

Checking for Duplicates and Null Values

In [99]:
data = data.fillna('0')
null = data.isna().values.any()
duplicates = data.duplicated().values.any()
print(f"Null values ? : {null}\nDuplicate values ? : {duplicates}")

Null values ? : False
Duplicate values ? : False


Splitting the Data as Target and Features

In [121]:
from sklearn.preprocessing import LabelEncoder

In [133]:
X = data.iloc[:, [1,2,3,4,5,11]].values
y = data.iloc[: , 8].values

In [142]:
enc = LabelEncoder()
indices = [0,1,2,3,4,5]
for i in indices:
  enc.fit(X[:, i])
  X[:, i] = enc.transform(X[:, i])
X

array([[2, 1, 0, 0, 1, 2],
       [2, 1, 1, 0, 1, 2],
       [2, 1, 2, 0, 1, 2],
       ...,
       [2, 0, 0, 0, 1, 1],
       [2, 1, 0, 0, 1, 0],
       [2, 0, 0, 0, 2, 0]], dtype=object)

Importing ML algorithms and splitting the dataset as Training Set and Test Set

In [147]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

print(X_train[0:10])

[[2 1 2 0 1 2]
 [1 0 0 0 1 2]
 [2 0 1 0 1 1]
 [1 1 0 0 1 2]
 [2 0 0 0 1 2]
 [2 1 2 0 0 2]
 [2 1 0 0 1 1]
 [2 1 2 1 1 1]
 [1 0 0 0 1 1]
 [2 1 1 0 0 2]]


In [150]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

gen = {'Male':0, 'Female':1}
mar = {'No':0, 'Yes':1}
dep = {'0':0, '1':1, '3+':2, '2':3}
edu = {'Not Graduate':0, 'Graduate':1}
emp = {'No': 0, '0': 0, 'Yes':1}
prop = {'Urban': 0, 'Semiurban': 1}


In [152]:
q1 = input('Enter your Gender: ').title()
q2 = input('Are you married?: ').title()
q3 = input('No.of Dependencies: ')
q4 = input('Education Status: ').title()
q5 = input('Are you self-employed?: ').title()
q6 = input('Location of Property?: ').title()

result = regressor.predict([[gen[q1], mar[q2], dep[q3], edu[q4], emp[q5], prop[q6]]])
print(f"Your Loan Amount would be : $ {result[0]}")

Enter your Gender: Female
Are you married?: No
No.of Dependencies: 0
Education Status: Graduate
Are you self-employed?: Yes
Location of Property?: Urban
Your Loan Amount would be : $92.81529514522322
